 - name: Mon premier playbook
   hosts: all
   become: yes
   tasks:
     - name: Test de connexion
       ping:

     - name: Creation de répertoire
       file:
         path: "/tmp/pmerle/1/2/3/4"
         state: directory
         recurse: yes
         owner: root
         group: root
         mode: 0755

