 - name: mon playbook
   hosts: all
   become: yes
   tasks:

    - name: test lineinfile
      lineinfile:
        dest: /tmp/test.conf
        line: "test 2"
        regexp: "^test$"
        state: present
      
