 - name: mon playbook
   hosts: all
   become: yes
   tasks:

    - name: test lineinfile
      lineinfile:
        dest: /tmp/test.conf
        regexp: "^Ma"
        state: absent
        backup: yes
      
